micronaut:
  application:
    name: kestra
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      ui:
        paths: classpath:ui
        mapping: /ui/**

  server:
    max-request-size: 10GB
    multipart:
      max-file-size: 10GB
      disk: true
    read-idle-timeout: 5m
    write-idle-timeout: 5m
    idle-timeout: 5m
    netty:
      max-chunk-size: 10MB

jackson:
  serialization:
    writeDatesAsTimestamps: false

endpoints:
  all:
    port: 8081
    enabled: true
    sensitive: false
  health:
    details-visible: ANONYMOUS

kestra:
  kafka:
    defaults:
      topic:
        partitions: 64
        replication-factor: 1
        properties:
          compression.type: "lz4"

      consumer:
        properties:
          isolation.level: "read_committed"
          auto.offset.reset: "earliest"
          enable.auto.commit: "false"

      producer:
        properties:
          acks: "all"

      stream:
        properties:
          processing.guarantee: "exactly_once"
          replication.factor: "${kestra.kafka.defaults.topic.replication-factor}"
          acks: "all"

    topics:
      org-kestra-core-models-executions-execution:
        name: "kestra_execution"
        properties:
          cleanup.policy: "compact"
          retention.ms: "-1"

      org-kestra-core-runners-workertask:
        name: "kestra_workertask"

      org-kestra-core-runners-workertaskresult:
        name: "kestra_workertaskresult"

  elasticsearch:
    indices:
      flows:
        index: "kestra_flows"
        cls: org.kestra.core.models.flows.Flow
        mapping-file: flow
      flows-revisions:
        index: "kestra_flows_revisions"
        cls: org.kestra.core.models.flows.Flow
        mapping-file: flow
      executions:
        index: "kestra_executions"
        cls: org.kestra.core.models.executions.Execution
        mapping-file: execution


  plugins:
    repositories:
      central:
        url: https://repo.maven.apache.org/maven2/
      jcenter:
        url: https://jcenter.bintray.com/
      kestra:
        url: https://dl.bintray.com/kestra/maven

  variables:
    env-vars-prefix: KESTRA_
    globals: {}

  metrics:
    prefix: kestra